#!/usr/bin/env python3
"""
Populates feast_calendar table: month/day → saint → associated personal names in 4 languages.
Static content based on the Roman Catholic liturgical calendar.
"""
import json

# Format: (month, day, saint_name, names_it, names_en, names_es, names_pt, feast_rank)
FEAST_CALENDAR = [
    # January
    (1,  1,  "Mary, Mother of God",          ["Maria","Marianna","Mariella","Maristella"], ["Mary","Marie","Maria"], ["María","Marisol","Mariela"], ["Maria","Mariana","Mariela"], "solemnity"),
    (1,  2,  "Basil and Gregory",             ["Basilio","Gregorio","Gori"], ["Basil","Gregory","Greg"], ["Basilio","Gregorio"], ["Basílio","Gregório"], "memorial"),
    (1,  3,  "Genevieve",                     ["Genoveffa","Genoveva"], ["Genevieve"], ["Genoveva"], ["Genoveva"], "optional"),
    (1,  6,  "Epiphany",                      ["Epifanio","Tifania"], ["Epiphany"], ["Epifanio"], ["Epifânio"], "solemnity"),
    (1,  7,  "Raymond of Penyafort",          ["Raimondo","Raimonda","Ramona"], ["Raymond","Ramon"], ["Raimundo","Ramón","Ramona"], ["Raimundo","Ramona"], "memorial"),
    (1,  13, "Hilary of Poitiers",            ["Ilario","Ilaria"], ["Hilary","Hillary"], ["Hilario","Hilaria"], ["Hilário","Hilária"], "memorial"),
    (1,  17, "Anthony the Great",             ["Antonio","Antonia","Antonella","Toni","Tonino"], ["Anthony","Tony","Antony"], ["Antonio","Antonia","Toño"], ["Antônio","Antônia","Toni"], "memorial"),
    (1,  20, "Fabian",                        ["Fabiano","Fabiana"], ["Fabian"], ["Fabián","Fabiana"], ["Fabiano","Fabiana"], "optional"),
    (1,  20, "Sebastian",                     ["Sebastiano","Sebastiana"], ["Sebastian"], ["Sebastián","Sebastiana"], ["Sebastião","Sebastiana"], "optional"),
    (1,  21, "Agnes of Rome",                 ["Agnese","Agnese"], ["Agnes"], ["Inés","Inés"], ["Inês","Inês"], "memorial"),
    (1,  22, "Vincent of Saragossa",          ["Vincenzo","Vincenza","Enzo","Vince"], ["Vincent","Vince"], ["Vicente","Vincente"], ["Vicente","Vicença"], "optional"),
    (1,  24, "Francis de Sales",              ["Francesco","Francesca","Franco","Franca"], ["Francis","Frances","Frank","Fran"], ["Francisco","Francisca","Paco","Paca"], ["Francisco","Francisca","Chico","Chica"], "memorial"),
    (1,  25, "Conversion of Paul",            ["Paolo","Paola","Paolina"], ["Paul","Paula","Pauline"], ["Pablo","Paula","Paulina"], ["Paulo","Paula","Paulino"], "feast"),
    (1,  26, "Timothy and Titus",             ["Timoteo","Tito"], ["Timothy","Tim","Titus"], ["Timoteo","Tito"], ["Timóteo","Tito"], "memorial"),
    (1,  27, "Angela Merici",                 ["Angela","Angelica","Angelina"], ["Angela","Angel","Angelica"], ["Ángela","Angelica","Angelina"], ["Ângela","Angelica","Angelina"], "memorial"),
    (1,  28, "Thomas Aquinas",                ["Tommaso","Tom"], ["Thomas","Tom","Tommy"], ["Tomás","Tomasa"], ["Tomás","Tomé"], "memorial"),
    (1,  31, "John Bosco",                    ["Giovanni","Gianni","Gianni","Ivan","Giovanna"], ["John","Johnny","Joan","Jean"], ["Juan","Juana","Juanito"], ["João","Joana","Jean"], "memorial"),
    # February
    (2,  2,  "Presentation of the Lord",     ["Simone","Simona"], ["Simon","Simone"], ["Simeón","Simona"], ["Simeão","Simona"], "feast"),
    (2,  3,  "Blaise of Sebaste",             ["Biagio"], ["Blaise","Blaze"], ["Blas"], ["Brás"], "optional"),
    (2,  5,  "Agatha of Sicily",              ["Agata","Agatha"], ["Agatha"], ["Ágata"], ["Ágata"], "memorial"),
    (2,  6,  "Paul Miki",                     ["Paolo","Paola"], ["Paul","Paula"], ["Pablo","Paula"], ["Paulo","Paula"], "memorial"),
    (2,  10, "Scholastica",                   ["Scolastica"], ["Scholastica"], ["Escolástica"], ["Escolástica"], "memorial"),
    (2,  11, "Our Lady of Lourdes",           ["Lourdes","Lourdinha"], ["Lourdes"], ["Lourdes"], ["Lourdes"], "optional"),
    (2,  14, "Cyril and Methodius",           ["Cirillo","Metodio"], ["Cyril","Methodius"], ["Cirilo","Metodio"], ["Cirilo","Metódio"], "memorial"),
    (2,  22, "Chair of Peter",                ["Pietro","Pietra","Piero","Petra"], ["Peter","Pete","Petra"], ["Pedro","Petra","Pedrín"], ["Pedro","Petra"], "feast"),
    (2,  23, "Polycarp",                      ["Policarpo"], ["Polycarp"], ["Policarpo"], ["Policarpo"], "memorial"),
    # March
    (3,  4,  "Casimir",                       ["Casimiro"], ["Casimir"], ["Casimiro"], ["Casimiro"], "optional"),
    (3,  7,  "Perpetua and Felicity",         ["Perpetua","Felicita","Felice","Felicia"], ["Perpetua","Felicity","Felicia"], ["Perpetua","Felicidad","Felicia"], ["Perpétua","Felicidade","Felícia"], "memorial"),
    (3,  8,  "John of God",                   ["Giovanni di Dio"], ["John"], ["Juan de Dios"], ["João de Deus"], "memorial"),
    (3,  9,  "Frances of Rome",               ["Francesca"], ["Frances","Fran"], ["Francisca","Paca","Fran"], ["Francisca","Chica"], "optional"),
    (3,  17, "Patrick of Ireland",            ["Patrizio","Patrizia"], ["Patrick","Pat","Patricia"], ["Patricio","Patricia"], ["Patrício","Patrícia"], "optional"),
    (3,  18, "Cyril of Jerusalem",            ["Cirillo"], ["Cyril"], ["Cirilo"], ["Cirilo"], "optional"),
    (3,  19, "Joseph",                        ["Giuseppe","Giuseppina","Peppe","Beppe","Peppa","Josè"], ["Joseph","Joe","Josephine","Josie"], ["José","Josefa","Pepe","Josefina"], ["José","Josefa","Zé","Josefina"], "solemnity"),
    (3,  23, "Turibius of Mogrovejo",         ["Toribio"], ["Turibius"], ["Toribio"], ["Toríbio"], "optional"),
    (3,  25, "Annunciation",                  ["Annunziata","Nunzia"], [""], ["Anunciación"], ["Anunciata"], "solemnity"),
    # April
    (4,  2,  "Francis of Paola",              ["Francesco","Francesca","Franco","Franca"], ["Francis","Frances"], ["Francisco","Francisca"], ["Francisco","Francisca"], "optional"),
    (4,  4,  "Isidore of Seville",            ["Isidoro","Isidora"], ["Isidore"], ["Isidoro","Isidora"], ["Isidoro","Isidora"], "optional"),
    (4,  5,  "Vincent Ferrer",                ["Vincenzo","Vincenza"], ["Vincent"], ["Vicente"], ["Vicente"], "optional"),
    (4,  7,  "John Baptist de la Salle",      ["Giovanni Battista"], ["John","Baptist"], ["Juan Bautista"], ["João Batista"], "memorial"),
    (4,  11, "Stanislaus",                    ["Stanislao","Stanislava"], ["Stanislaus","Stan"], ["Estanislao"], ["Estanislau"], "memorial"),
    (4,  13, "Martin I",                      ["Martino","Martina"], ["Martin","Martina"], ["Martín","Martina"], ["Martinho","Martina"], "optional"),
    (4,  21, "Anselm of Canterbury",          ["Anselmo","Anselma"], ["Anselm"], ["Anselmo"], ["Anselmo"], "optional"),
    (4,  23, "George",                        ["Giorgio","Giorgia","Giorgina","Juri","Jurij"], ["George","Georgia","Georgina"], ["Jorge","Georgina"], ["Jorge","Georgina"], "optional"),
    (4,  24, "Fidelis of Sigmaringen",        ["Fedele"], ["Fidelis"], ["Fidel","Fidela"], ["Fidel","Fidela"], "optional"),
    (4,  25, "Mark the Evangelist",           ["Marco","Marca"], ["Mark","Marcus","Marc"], ["Marcos","Marco"], ["Marcos","Marco"], "feast"),
    (4,  28, "Peter Chanel",                  ["Pietro","Piero"], ["Peter","Pete"], ["Pedro"], ["Pedro"], "optional"),
    (4,  29, "Catherine of Siena",            ["Caterina","Catia","Katia","Katerina"], ["Catherine","Cathy","Kate","Katie"], ["Catalina","Catia","Katerina"], ["Catarina","Catia","Katerina"], "feast"),
    (4,  30, "Pius V",                        ["Pio"], ["Pius"], ["Pío"], ["Pio"], "optional"),
    # May
    (5,  1,  "Joseph the Worker",             ["Giuseppe","Josè"], ["Joseph","Joe"], ["José","Pepe"], ["José","Zé"], "optional"),
    (5,  2,  "Athanasius",                    ["Atanasio","Anastasio","Anastasia"], ["Athanasius"], ["Atanasio","Anastasio"], ["Atanásio","Anastásio"], "memorial"),
    (5,  3,  "Philip and James",              ["Filippo","Giacomo","Giacomina","Jacopo"], ["Philip","Philip","James","Jim","Jamie"], ["Felipe","Jaime","Jacobo"], ["Filipe","Tiago","Jaime"], "feast"),
    (5,  14, "Matthias",                      ["Mattia","Matteo","Mattia"], ["Matthias","Matthew","Matt"], ["Matías","Mateo"], ["Matias","Mateus"], "feast"),
    (5,  18, "John I",                        ["Giovanni","Gianni"], ["John","Johnny"], ["Juan","Juanito"], ["João","Joãozinho"], "optional"),
    (5,  20, "Bernardine of Siena",           ["Bernardino","Bernardo","Nardo"], ["Bernardine","Bernard"], ["Bernardino","Bernardo"], ["Bernardino","Bernardo"], "optional"),
    (5,  22, "Rita of Cascia",                ["Rita"], ["Rita"], ["Rita"], ["Rita"], "optional"),
    (5,  25, "Bede the Venerable",            ["Beda"], ["Bede"], ["Beda"], ["Beda"], "optional"),
    (5,  25, "Gregory VII",                   ["Gregorio","Gori"], ["Gregory","Greg"], ["Gregorio"], ["Gregório"], "optional"),
    (5,  26, "Philip Neri",                   ["Filippo","Neri"], ["Philip","Neri"], ["Felipe","Neri"], ["Filipe","Neri"], "memorial"),
    (5,  27, "Augustine of Canterbury",       ["Agostino","Agostina","Augusto","Augusta"], ["Augustine","Austin","August","Augusta"], ["Agustín","Augusta"], ["Agostinho","Augusta"], "optional"),
    (5,  31, "Visitation of Mary",            ["Visitazione"], ["Visitation"], ["Visitación"], ["Visitação"], "feast"),
    # June
    (6,  1,  "Justin",                        ["Giustino","Giusto","Giusta"], ["Justin","Justine"], ["Justino","Justina"], ["Justino","Justina"], "memorial"),
    (6,  3,  "Charles Lwanga",                ["Carlo","Carla","Luca","Luce"], ["Charles","Carl","Charlie"], ["Carlos","Carla","Charlot"], ["Carlos","Carla","Charlie"], "memorial"),
    (6,  5,  "Boniface",                      ["Bonifacio"], ["Boniface","Bonnie"], ["Bonifacio"], ["Bonifácio"], "memorial"),
    (6,  6,  "Norbert",                       ["Norberto"], ["Norbert"], ["Norberto"], ["Norberto"], "optional"),
    (6,  9,  "Ephrem",                        ["Efrem"], ["Ephrem"], ["Efrem"], ["Efrem"], "optional"),
    (6,  11, "Barnabas",                      ["Barnaba"], ["Barnabas","Barney"], ["Bernabé"], ["Barnabé"], "memorial"),
    (6,  13, "Anthony of Padua",              ["Antonio","Antonia","Antonella","Toni","Tonino"], ["Anthony","Tony","Antony"], ["Antonio","Antonia","Toño"], ["Antônio","Antônia","Toni"], "memorial"),
    (6,  19, "Romuald",                       ["Romualdo"], ["Romuald"], ["Romualdo"], ["Romualdo"], "optional"),
    (6,  21, "Aloysius Gonzaga",              ["Luigi","Luisa","Alvise","Gino"], ["Louis","Louise","Lewis","Aloysius"], ["Luis","Luisa","Aloysius"], ["Luís","Luísa","Aloisio"], "memorial"),
    (6,  22, "Paulinus of Nola",              ["Paolino","Paolina"], ["Paulinus","Paul","Pauline"], ["Paulino","Paulina"], ["Paulino","Paulina"], "optional"),
    (6,  22, "John Fisher",                   ["Giovanni","Gianni"], ["John","Johnny"], ["Juan"], ["João"], "optional"),
    (6,  22, "Thomas More",                   ["Tommaso","Tom"], ["Thomas","Tom","Tommy"], ["Tomás"], ["Tomás","Tomé"], "optional"),
    (6,  24, "Birth of John the Baptist",     ["Giovanni","Gianni","Gianfranco","Giambattista","Ivan","Giovanna"], ["John","Johnny","Joan","Jean","Jan"], ["Juan","Juana","Juanito"], ["João","Joana","Jean","Jan"], "solemnity"),
    (6,  27, "Cyril of Alexandria",           ["Cirillo"], ["Cyril"], ["Cirilo"], ["Cirilo"], "optional"),
    (6,  28, "Irenaeus",                      ["Ireneo"], ["Irenaeus"], ["Ireneo"], ["Irineu"], "memorial"),
    (6,  29, "Peter and Paul",                ["Pietro","Piero","Pietra","Paolo","Paola"], ["Peter","Pete","Paul","Paula"], ["Pedro","Pablo","Petra","Paula"], ["Pedro","Paulo","Petra","Paula"], "solemnity"),
    (6,  30, "First Martyrs of Rome",         [], [], [], [], "optional"),
    # July
    (7,  3,  "Thomas the Apostle",            ["Tommaso","Tom","Tommasino"], ["Thomas","Tom","Tommy"], ["Tomás","Tomasa","Tomas"], ["Tomé","Tomás"], "feast"),
    (7,  4,  "Elizabeth of Portugal",         ["Elisabetta","Elisa","Lisa","Betta","Elsa"], ["Elizabeth","Elisabeth","Elisa","Lisa","Beth","Liz"], ["Isabel","Isabela","Isa","Elisa"], ["Isabel","Isabela","Isa","Elisa"], "optional"),
    (7,  5,  "Anthony Mary Zaccaria",         ["Antonio","Antonia"], ["Anthony","Tony"], ["Antonio","Antonia"], ["Antônio","Antônia"], "optional"),
    (7,  6,  "Maria Goretti",                 ["Maria","Marianna","Mariella"], ["Mary","Marie","Maria"], ["María","Marisol"], ["Maria","Mariana"], "optional"),
    (7,  9,  "Augustine Zhao Rong",           ["Agostino","Augusto"], ["Augustine","August"], ["Agustín"], ["Agostinho"], "optional"),
    (7,  11, "Benedict",                      ["Benedetto","Benedetta","Bene"], ["Benedict","Ben","Benny","Benedicta"], ["Benito","Benita","Bene"], ["Benedito","Benedita","Bene"], "feast"),
    (7,  13, "Henry",                         ["Enrico","Enrica","Rico"], ["Henry","Harry","Harriet"], ["Enrique","Enriqueta","Quique"], ["Henrique","Henriqueta","Quique"], "optional"),
    (7,  14, "Camillus de Lellis",            ["Camillo","Camilla"], ["Camillus","Camilla"], ["Camilo","Camila"], ["Camilo","Camila"], "optional"),
    (7,  15, "Bonaventure",                   ["Bonaventura"], ["Bonaventure"], ["Buenaventura"], ["Boaventura"], "memorial"),
    (7,  16, "Our Lady of Mount Carmel",      ["Carmela","Carmelina","Carmelo","Carmine"], ["Carmen","Carmel","Carmela"], ["Carmen","Carmela","Carmelita"], ["Carmo","Carmem","Carmela"], "optional"),
    (7,  20, "Apollinaris",                   ["Apollinare","Apollonia"], ["Apollinaris","Apollonia"], ["Apolinar"], ["Apolinário"], "optional"),
    (7,  21, "Lawrence of Brindisi",          ["Lorenzo","Lorenza","Lori","Enzo"], ["Lawrence","Larry","Laura","Lauren"], ["Lorenzo","Lorenza","Laura"], ["Lourenço","Lourença","Laura"], "optional"),
    (7,  22, "Mary Magdalene",                ["Maddalena","Lena"], ["Magdalene","Magdalen","Madeleine","Maddie"], ["Magdalena","Magda"], ["Madalena","Magda"], "feast"),
    (7,  23, "Bridget of Sweden",             ["Brigida","Brigitta"], ["Bridget","Bridgit","Brigid"], ["Brígida"], ["Brígida"], "feast"),
    (7,  24, "Charbel Makhlouf",              ["Charbel","Sharbel"], ["Charbel"], ["Charbel"], ["Charbel"], "optional"),
    (7,  25, "James the Apostle",             ["Giacomo","Jacopo","Diego"], ["James","Jim","Jamie","Jacob","Jake"], ["Jaime","Jacobo","Diego"], ["Tiago","Jaime","Diogo"], "feast"),
    (7,  26, "Joachim and Anne",              ["Gioacchino","Anna","Annalisa","Annamaria"], ["Joachim","Anne","Ann","Anna"], ["Joaquín","Ana","Anita"], ["Joaquim","Ana","Anita"], "memorial"),
    (7,  29, "Martha",                        ["Marta"], ["Martha","Marta"], ["Marta"], ["Marta"], "memorial"),
    (7,  29, "Lazarus",                       ["Lazzaro"], ["Lazarus"], ["Lázaro"], ["Lázaro"], "memorial"),
    (7,  30, "Peter Chrysologus",             ["Pietro","Piero"], ["Peter","Pete"], ["Pedro"], ["Pedro"], "optional"),
    (7,  31, "Ignatius of Loyola",            ["Ignazio","Ignazina"], ["Ignatius","Iggy"], ["Ignacio","Nacho"], ["Inácio"], "memorial"),
    # August
    (8,  1,  "Alphonsus Liguori",             ["Alfonso","Alfonsina","Fonso"], ["Alphonsus","Alfonso"], ["Alfonso","Alfonsa"], ["Afonso","Afonsa"], "memorial"),
    (8,  4,  "John Vianney",                  ["Giovanni","Gianni"], ["John","Johnny"], ["Juan"], ["João"], "memorial"),
    (8,  6,  "Transfiguration",               [""], [""], [""], [""], "feast"),
    (8,  7,  "Sixtus II",                     ["Sisto","Sistina"], ["Sixtus"], ["Sixto"], ["Sisto"], "optional"),
    (8,  8,  "Dominic",                       ["Domenico","Domenica","Nico","Mimmo"], ["Dominic","Dominica","Nick"], ["Domingo","Dominga","Dominguito"], ["Domingos","Dominga"], "memorial"),
    (8,  10, "Lawrence of Rome",              ["Lorenzo","Lorenza","Lori","Enzo"], ["Lawrence","Larry","Laura","Lauren"], ["Lorenzo","Lorenza","Laura"], ["Lourenço","Lourença","Laura"], "feast"),
    (8,  11, "Clare of Assisi",               ["Chiara","Clara","Clarissa","Clarice"], ["Clare","Clara","Claire","Clarissa"], ["Clara","Clarissa","Clarice"], ["Clara","Clarissa","Clarice"], "memorial"),
    (8,  12, "Jane Frances de Chantal",       ["Giovanna","Gianna","Francesca","Franca"], ["Jane","Jeanne","Frances","Fran"], ["Juana","Juanita","Francisca"], ["Joana","Júlia","Francisca"], "optional"),
    (8,  13, "Pontian and Hippolytus",        ["Ponziano","Ippolito"], ["Pontian","Hippolytus"], ["Ponciano","Hipólito"], ["Ponciano","Hipólito"], "optional"),
    (8,  14, "Maximilian Kolbe",              ["Massimiliano"], ["Maximilian","Max"], ["Maximiliano","Max"], ["Maximiliano","Max"], "memorial"),
    (8,  15, "Assumption of Mary",            ["Maria","Marianna","Mariella","Maristella","Assunta"], ["Mary","Marie","Maria"], ["María","Asunción","Asun"], ["Maria","Assunção"], "solemnity"),
    (8,  16, "Stephen of Hungary",            ["Stefano","Stefania","Steve"], ["Stephen","Steve","Stephanie"], ["Esteban","Estefanía","Steve"], ["Estêvão","Estefânia","Steve"], "optional"),
    (8,  20, "Bernard of Clairvaux",          ["Bernardo","Bernardino","Nardo"], ["Bernard","Bernie","Bernardine"], ["Bernardo","Bernardino"], ["Bernardo","Bernardino"], "memorial"),
    (8,  21, "Pius X",                        ["Pio"], ["Pius"], ["Pío"], ["Pio"], "memorial"),
    (8,  22, "Queenship of Mary",             ["Maria","Marianna","Mariella","Regina"], ["Mary","Marie","Maria","Regina"], ["María","Regina"], ["Maria","Regina"], "memorial"),
    (8,  24, "Bartholomew",                   ["Bartolomeo","Bortolo","Meo"], ["Bartholomew","Bart"], ["Bartolomé","Bartolome","Barto"], ["Bartolomeu","Barto"], "feast"),
    (8,  25, "Louis IX of France",            ["Luigi","Luisa","Gigi","Alvise"], ["Louis","Louise","Lewis","Lou"], ["Luis","Luisa","Lou"], ["Luís","Luísa","Lou"], "optional"),
    (8,  27, "Monica",                        ["Monica","Monika"], ["Monica","Monika"], ["Mónica","Monika"], ["Mônica","Monika"], "memorial"),
    (8,  28, "Augustine of Hippo",            ["Agostino","Agostina","Augusto","Augusta"], ["Augustine","Austin","August","Augusta"], ["Agustín","Augusta"], ["Agostinho","Augusta"], "memorial"),
    (8,  29, "Beheading of John the Baptist", ["Giovanni","Gianni"], ["John","Johnny"], ["Juan","Juanito"], ["João","Joãozinho"], "memorial"),
    # September
    (9,  3,  "Gregory the Great",             ["Gregorio","Gori"], ["Gregory","Greg"], ["Gregorio"], ["Gregório"], "memorial"),
    (9,  8,  "Birth of Mary",                 ["Maria","Marianna","Mariella","Maristella"], ["Mary","Marie","Maria"], ["María","Marisol"], ["Maria","Mariana"], "feast"),
    (9,  9,  "Peter Claver",                  ["Pietro","Piero"], ["Peter","Pete"], ["Pedro"], ["Pedro"], "memorial"),
    (9,  13, "John Chrysostom",               ["Giovanni","Gianni"], ["John","Johnny"], ["Juan","Juanito"], ["João","Joãozinho"], "memorial"),
    (9,  14, "Exaltation of the Cross",       ["Esaltazione"], [""], ["Cruz","Crucita"], ["Cruz","Santa Cruz"], "feast"),
    (9,  15, "Our Lady of Sorrows",           ["Addolorata","Dolores","Lola"], ["Dolores","Lola"], ["Dolores","Lola","Lolita"], ["Dores","Dolores"], "memorial"),
    (9,  16, "Cornelius and Cyprian",         ["Cornelio","Cipriano"], ["Cornelius","Cyprian"], ["Cornelio","Cipriano"], ["Cornélio","Cipriano"], "memorial"),
    (9,  17, "Robert Bellarmine",             ["Roberto","Roberta"], ["Robert","Bob","Bobby","Roberta"], ["Roberto","Roberta","Rober"], ["Roberto","Roberta","Bob"], "optional"),
    (9,  19, "Januarius",                     ["Gennaro","Gennaio"], ["Januarius","Gennaro"], ["Jenaro"], ["Genário"], "optional"),
    (9,  20, "Andrew Kim Tae-gon",            ["Andrea","Andea"], ["Andrew","Andy","Andrea"], ["Andrés","Andrea"], ["André","André"], "memorial"),
    (9,  21, "Matthew",                       ["Matteo","Mattia"], ["Matthew","Matt","Matthias"], ["Mateo","Matías"], ["Mateus","Matias"], "feast"),
    (9,  23, "Padre Pio",                     ["Pio","Pieno"], ["Pio","Pius"], ["Pío"], ["Pio"], "memorial"),
    (9,  26, "Cosmas and Damian",             ["Cosma","Damiano"], ["Cosmas","Damian"], ["Cosme","Damián"], ["Cosme","Damião"], "optional"),
    (9,  27, "Vincent de Paul",               ["Vincenzo","Vincenza","Enzo"], ["Vincent","Vince"], ["Vicente"], ["Vicente"], "memorial"),
    (9,  28, "Wenceslaus",                    ["Venceslao"], ["Wenceslaus","Wenzel"], ["Wenceslao"], ["Venceslau"], "optional"),
    (9,  29, "Michael, Gabriel, Raphael",     ["Michele","Gabriele","Raffaele","Michi","Rafe"], ["Michael","Mike","Gabriel","Gabe","Raphael","Rafael"], ["Miguel","Gabriel","Rafael","Rafa"], ["Miguel","Gabriel","Rafael"], "feast"),
    (9,  30, "Jerome",                        ["Gerolamo","Girolamo","Geronimo","Remo"], ["Jerome","Jerry"], ["Jerónimo","Geronimo","Jeronimo"], ["Jerônimo","Geronimo"], "memorial"),
    # October
    (10, 1,  "Thérèse of Lisieux",            ["Teresa","Teresina","Teri"], ["Theresa","Teresa","Terry","Tess"], ["Teresa","Teresita"], ["Teresa","Teresinha"], "memorial"),
    (10, 2,  "Guardian Angels",               ["Angelo","Angela","Angelica","Angelina"], ["Angel","Angela","Angelica"], ["Ángel","Ángela","Angelica"], ["Ângelo","Ângela","Angelica"], "memorial"),
    (10, 4,  "Francis of Assisi",             ["Francesco","Francesca","Franco","Franca"], ["Francis","Frances","Frank","Fran"], ["Francisco","Francisca","Paco","Paca"], ["Francisco","Francisca","Chico","Chica"], "memorial"),
    (10, 6,  "Bruno of Cologne",              ["Bruno"], ["Bruno"], ["Bruno"], ["Bruno"], "optional"),
    (10, 7,  "Our Lady of the Rosary",        ["Rosaria","Rosario","Rosa"], ["Rosario","Rosaria","Rosa","Rosemary"], ["Rosario","Rosaria","Rosarito"], ["Rosário","Rosaria","Rosa"], "memorial"),
    (10, 9,  "Denis of Paris",                ["Dionisio","Dino"], ["Denis","Dennis","Denise"], ["Dionisio","Denís"], ["Dionísio","Denis"], "optional"),
    (10, 14, "Callixtus I",                   ["Callisto"], ["Callixtus"], ["Calixto"], ["Calisto"], "optional"),
    (10, 15, "Teresa of Ávila",               ["Teresa","Teresina","Teri"], ["Theresa","Teresa","Terry","Tess"], ["Teresa","Teresita"], ["Teresa","Teresinha"], "memorial"),
    (10, 16, "Hedwig of Silesia",             ["Edvige","Edvighe"], ["Hedwig","Hedvige"], ["Eduvigis","Eduviges"], ["Edwiges"], "optional"),
    (10, 16, "Margaret Mary Alacoque",        ["Margherita","Rita","Margaux"], ["Margaret","Maggie","Peggy","Rita"], ["Margarita","Margot","Rita"], ["Margarida","Rita","Magda"], "optional"),
    (10, 17, "Ignatius of Antioch",           ["Ignazio"], ["Ignatius"], ["Ignacio"], ["Inácio"], "memorial"),
    (10, 18, "Luke the Evangelist",           ["Luca","Lucio","Luciana"], ["Luke","Lucian","Lucy"], ["Lucas","Luciano","Lucía"], ["Lucas","Luciano","Lúcia"], "feast"),
    (10, 19, "Jean de Brébeuf",               ["Giovanni","Gianni"], ["John","Jean","Jacques"], ["Juan"], ["João","Jean"], "memorial"),
    (10, 22, "John Paul II",                  ["Giovanni Paolo","Gianni","Paolo"], ["John Paul","Jean-Paul"], ["Juan Pablo"], ["João Paulo"], "optional"),
    (10, 23, "John of Capistrano",            ["Giovanni","Gianni"], ["John","Johnny"], ["Juan"], ["João"], "optional"),
    (10, 24, "Anthony Mary Claret",           ["Antonio","Antonia"], ["Anthony","Tony"], ["Antonio","Antonia"], ["Antônio","Antônia"], "optional"),
    (10, 28, "Simon and Jude",                ["Simone","Simona","Giuda"], ["Simon","Jude"], ["Simeón","Judas"], ["Simeão","Judas"], "feast"),
    # November
    (11, 1,  "All Saints",                    [], [], [], [], "solemnity"),
    (11, 2,  "All Souls",                     [], [], [], [], "commemoration"),
    (11, 3,  "Martin de Porres",              ["Martino","Martina"], ["Martin","Martina"], ["Martín","Martina"], ["Martinho","Martina"], "optional"),
    (11, 4,  "Charles Borromeo",              ["Carlo","Carla","Carlotta","Carlino"], ["Charles","Charlie","Carl","Charlotte"], ["Carlos","Carla","Carlota"], ["Carlos","Carla","Carlota"], "memorial"),
    (11, 9,  "Dedication of the Lateran",     [], [], [], [], "feast"),
    (11, 10, "Leo the Great",                 ["Leone","Leonida","Leo"], ["Leo","Leon","Leonidas"], ["León","Leonidas"], ["Leão","Leonidas"], "memorial"),
    (11, 11, "Martin of Tours",               ["Martino","Martina"], ["Martin","Martina"], ["Martín","Martina"], ["Martinho","Martina"], "memorial"),
    (11, 12, "Josaphat",                      ["Giosafat"], ["Josaphat"], ["Josafat"], ["Josafá"], "memorial"),
    (11, 13, "Frances Xavier Cabrini",        ["Francesca","Franca"], ["Frances","Fran","Francesca"], ["Francisca","Paca"], ["Francisca","Chica"], "optional"),
    (11, 15, "Albert the Great",              ["Alberto","Alberta","Berto"], ["Albert","Al","Alberta"], ["Alberto","Alberta","Berto"], ["Alberto","Alberta","Beto"], "optional"),
    (11, 16, "Margaret of Scotland",          ["Margherita","Rita"], ["Margaret","Maggie","Peggy"], ["Margarita","Margot"], ["Margarida"], "optional"),
    (11, 17, "Elizabeth of Hungary",          ["Elisabetta","Elisa","Lisa","Betta","Elsa"], ["Elizabeth","Elisabeth","Elisa","Lisa","Beth","Liz"], ["Isabel","Isabela","Isa","Elisa"], ["Isabel","Isabela","Isa","Elisa"], "memorial"),
    (11, 18, "Rose Philippine Duchesne",      ["Filomena","Rosa"], ["Rose","Rosemary","Rosa"], ["Rosa","Rosario"], ["Rosa","Rosária"], "optional"),
    (11, 21, "Presentation of Mary",          ["Maria","Marianna"], ["Mary","Marie","Maria"], ["María"], ["Maria"], "memorial"),
    (11, 22, "Cecilia",                       ["Cecilia","Cecily"], ["Cecilia","Cecily","Cece"], ["Cecilia","Cecily","Ceci"], ["Cecília","Ceci"], "memorial"),
    (11, 23, "Clement I",                     ["Clemente","Clemenza"], ["Clement","Clementine"], ["Clemente","Clementina"], ["Clemente","Clementina"], "optional"),
    (11, 23, "Columban",                      ["Colombano","Colomba"], ["Columban","Columba"], ["Colombano","Colomba"], ["Colombano","Colomba"], "optional"),
    (11, 25, "Catherine of Alexandria",       ["Caterina","Catia","Katia"], ["Catherine","Cathy","Kate"], ["Catalina","Catia"], ["Catarina","Catia"], "optional"),
    (11, 30, "Andrew",                        ["Andrea","Andea"], ["Andrew","Andy","Andrea"], ["Andrés","Andrea"], ["André","André"], "feast"),
    # December
    (12, 3,  "Francis Xavier",                ["Francesco","Francesca","Franco"], ["Francis","Frances","Frank"], ["Francisco","Francisca","Paco"], ["Francisco","Francisca","Chico"], "memorial"),
    (12, 4,  "John of Damascus",              ["Giovanni","Gianni"], ["John","Johnny"], ["Juan"], ["João"], "optional"),
    (12, 6,  "Nicholas of Myra",              ["Nicola","Nicolò","Nicoletta","Nico","Cola"], ["Nicholas","Nick","Nicky","Nicole"], ["Nicolás","Nicolasa","Nico"], ["Nicolau","Nicola","Nico"], "optional"),
    (12, 7,  "Ambrose",                       ["Ambrogio","Ambrosia"], ["Ambrose"], ["Ambrosio","Ambrosia"], ["Ambrósio","Ambrósia"], "memorial"),
    (12, 8,  "Immaculate Conception",         ["Immacolata","Maria","Concetta","Concettina"], ["Mary","Maria","Immaculata"], ["Inmaculada","Concepción","Concha","Conchi"], ["Imaculada","Conceição","Conça"], "solemnity"),
    (12, 9,  "Juan Diego",                    ["Diego","Juan Diego"], ["Diego","Juan","James"], ["Diego","Juan Diego"], ["Diogo","João Diogo"], "optional"),
    (12, 11, "Damasus I",                     ["Damaso"], ["Damasus"], ["Dámaso"], ["Dâmaso"], "optional"),
    (12, 12, "Our Lady of Guadalupe",         ["Guadalupe","Lupe"], ["Guadalupe","Lupe"], ["Guadalupe","Lupe","Lupita"], ["Guadalupe","Lupe"], "feast"),
    (12, 13, "Lucy of Syracuse",              ["Lucia","Luce","Luciana","Lucilla"], ["Lucy","Lucia","Luciana"], ["Lucía","Luciana","Luci"], ["Lúcia","Luciana","Luci"], "memorial"),
    (12, 14, "John of the Cross",             ["Giovanni","Gianni"], ["John","Johnny"], ["Juan"], ["João"], "memorial"),
    (12, 21, "Peter Canisius",                ["Pietro","Piero"], ["Peter","Pete"], ["Pedro"], ["Pedro"], "optional"),
    (12, 23, "John of Kanty",                 ["Giovanni","Gianni"], ["John","Johnny"], ["Juan"], ["João"], "optional"),
    (12, 26, "Stephen the first martyr",      ["Stefano","Stefania","Steve"], ["Stephen","Steve","Stephanie"], ["Esteban","Estefanía"], ["Estêvão","Estefânia"], "feast"),
    (12, 27, "John the Apostle",              ["Giovanni","Gianni","Gianfranco","Ivan","Giovanna"], ["John","Johnny","Joan","Jean"], ["Juan","Juana","Juanito"], ["João","Joana","Jean"], "feast"),
    (12, 28, "Holy Innocents",                ["Innocenzo","Innocenza"], ["Innocent","Innocence"], ["Inocencio","Inocencia"], ["Inocêncio","Inocência"], "feast"),
    (12, 29, "Thomas Becket",                 ["Tommaso","Tom"], ["Thomas","Tom","Tommy"], ["Tomás"], ["Tomás","Tomé"], "optional"),
    (12, 31, "Sylvester I",                   ["Silvestro","Silvestra"], ["Sylvester","Silvia"], ["Silvestre","Silvia"], ["Silvestre","Silvia"], "optional"),
]


def get_feast_calendar_rows() -> list[tuple]:
    rows = []
    for entry in FEAST_CALENDAR:
        month, day, saint_name, names_it, names_en, names_es, names_pt, feast_rank = entry
        rows.append((
            month, day, saint_name,
            json.dumps(names_it, ensure_ascii=False),
            json.dumps(names_en, ensure_ascii=False),
            json.dumps(names_es, ensure_ascii=False),
            json.dumps(names_pt, ensure_ascii=False),
            feast_rank,
        ))
    return rows


if __name__ == '__main__':
    rows = get_feast_calendar_rows()
    print(f"feast_calendar: {len(rows)} righe")
    for r in rows[:5]:
        print(r)
